### ISSUE TITLE
Search parameter: Add option to create a dataset from an url

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/WDKClient#208]
**_Relates to https://redmine.apidb.org/issues/5025_**

The dataset param type in WDK currently supports four types of inputs (text input, file input, basket, and strategy ID):
![image](https://user-images.githubusercontent.com/365139/166790880-95fad5de-458e-42cc-bbd6-7d2a574101b4.png)

We would like to add a fifth option, that allows a user to specify an URL. The GET response of the URL will be processed by the backend, similar to how file inputs are handled.

**TODOs**
_This isn't necessarily an exhaustive list of changes, but it should provide a good starting point._

- [x] Add a new `sourceType` called `url`: https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Views/Question/Params/DatasetParam.tsx#L47
- [x] Add a `section` entry: https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Views/Question/Params/DatasetParam.tsx#L135-L224
- [x] Add a new case in `datasetConfigPromise`: https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Views/Question/Params/DatasetParam.tsx#L331-L346
- [x] Update the `INIT_PARAM` case of the reducer to handle a `url` being included in the initial param data, similar to `idList`: https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Views/Question/Params/DatasetParam.tsx#L76-L86
- [x] Update https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Actions/DatasetParamActions.ts#L24
- [x] Update https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/StoreModules/QuestionStoreModule.ts#L845-L848
- [x] Update https://github.com/VEuPathDB/WDKClient/blob/a4a467c4afd9ae382e0463b0fb2fc81fd1b86d78/Client/src/Service/Mixins/DatasetsService.ts#L4-L21

**Comment by ryanrdoherty** [comment]
This is now supported on the backend.  See example usage details in the last comment in this issue: https://github.com/VEuPathDB/WDK/issues/27
